[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 4321
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"

# Enable deploy previews
[context.deploy-preview.environment]
  ENABLE_DEPLOY_PREVIEW = "true"

# Enable branch deploys
[context.branch-deploy.environment]
  ENABLE_BRANCH_DEPLOY = "true" 